

CREATE TABLE DEPTO (
   ID_DEPARTAMENTO      VARCHAR(3)           NOT NULL,
   ID_PAIS              VARCHAR(3),
   NOMBRE               VARCHAR(30)          NOT NULL,
   INDICATIVO           VARCHAR(3)           NOT NULL,
   FECHA_REGISTRO       TIMESTAMP WITH TIME  ZONE,
   FECHA_ACTUALIZACION  TIMESTAMP WITH TIME  ZONE,
   ESTADO               NUMERIC(10)           NOT NULL,
   ID_USUARIO           VARCHAR(15),
   iP_ADDRESS           VARCHAR(15)          NOT NULL,
   CONSTRAINT PK_DEPTO PRIMARY KEY (ID_DEPARTAMENTO)
);
