
CREATE TABLE ORGANIZACION_USUARIOS (
   ID_ORGANIZACION_USUARIO VARCHAR(50) NOT NULL,
   ID_ORGANIZACION         VARCHAR(50),
   ID_USUARIO              VARCHAR(50),
   CONSTRAINT PK_ORGANIZACION_USUARIOS PRIMARY KEY (ID_ORGANIZACION_USUARIO)
);
